library(dygraphs)
library(rCharts)
library(reshape2)

links1a = c("me1a_02", "me1a_03", "me1a_04", "me1a_05", "me1a_06", "me1a_07", "me1a_08", "me1a_09")
links1b = c("me1b_02", "me1b_03", "me1b_04", "me1b_05", "me1b_06", "me1b_07", "me1b_08", "me1b_09")
links2  = c("me2_02",  "me2_03",  "me2_04",  "me2_05",  "me2_06",  "me2_07",  "me2_08",  "me2_09")
links3  = c("me3_02",  "me3_03",  "me3_04",  "me3_05",  "me3_06",  "me3_07",  "me3_08",  "me3_09")
links4  = c("me4_02",  "me4_03",  "me4_04",  "me4_05",  "me4_06",  "me4_07",  "me4_08",  "me4_09")
linksn  = c("me1n_03", "me1n_06", "me1n_09", "me2n_03", "me2n_09", "me3n_03", "me3n_09", "me4n_03", "me4n_09")
#boards  = c("EMTF-1",  "EMTF-2",  "EMTF-3",  "EMTF-4",  "EMTF-5",  "EMTF-6",
#            "EMTF+1",  "EMTF+2",  "EMTF+3",  "EMTF+4",  "EMTF+5",  "EMTF+6")

dr <- read.csv(file="drifts.csv",header=T,sep=',')
df <- melt(dr, id = c("DateTime","board","rLength"), measure.vars = c(links1a, links1b, links2, links3, links4, linksn))
colnames(df) <- c("time", "board", "rLength", "link", "delay")

makeChart <- function(name,links,brd,len){
    d1 <- dPlot(x="time", y="delay", groups = c("link"), data = subset(df,(link %in% links) & board==brd & rLength>=len), type = "bubble")
    d1$xAxis(type = "addTimeAxis", inputFormat = "%Y.%m.%d %H:%M:%S", outputFormat = "%Y-%m-%d %H:%M") 
    d1$legend(x = 60, y = 10, width = 700, height = 20, horizontalAlign = "right")
    d1$addParams(dom = name)
    return(d1)
}
shinyServer(
  function(input, output) {

    output$me1a_links <- renderUI({ checkboxGroupInput('show_me1a_links', 'Links to show:', links1a, selected = links1a) })
    output$me1b_links <- renderUI({ checkboxGroupInput('show_me1b_links', 'Links to show:', links1b, selected = links1b) })
    output$me2_links  <- renderUI({ checkboxGroupInput('show_me2_links',  'Links to show:', links2,  selected = links2) })
    output$me3_links  <- renderUI({ checkboxGroupInput('show_me3_links',  'Links to show:', links3,  selected = links3) })
    output$me4_links  <- renderUI({ checkboxGroupInput('show_me4_links',  'Links to show:', links4,  selected = links4) })
    output$men_links  <- renderUI({ checkboxGroupInput('show_men_links',  'Links to show:', linksn,  selected = linksn) })
    output$all_links  <- renderUI({ checkboxGroupInput('show_all_links',  'Links to show:', c(links1a,links1b,links2,links3,links4,linksn), selected = c()) })

    output$me1a_run_length <- renderUI({ sliderInput('me1a_rl', 'Run Length', value = 100, min = 0, max = 100, step = 1) })
    output$me1b_run_length <- renderUI({ sliderInput('me1b_rl', 'Run Length', value = 100, min = 0, max = 100, step = 1) })
    output$me2_run_length  <- renderUI({ sliderInput('me2_rl',  'Run Length', value = 100, min = 0, max = 100, step = 1) })
    output$me3_run_length  <- renderUI({ sliderInput('me3_rl',  'Run Length', value = 100, min = 0, max = 100, step = 1) })
    output$me4_run_length  <- renderUI({ sliderInput('me4_rl',  'Run Length', value = 100, min = 0, max = 100, step = 1) })
    output$men_run_length  <- renderUI({ sliderInput('men_rl',  'Run Length', value = 100, min = 0, max = 100, step = 1) })
    output$all_run_length  <- renderUI({ sliderInput('all_rl',  'Run Length', value = 100, min = 0, max = 100, step = 1) })

    output$emtf_me1a_n1 <- renderChart({ makeChart("emtf_me1a_n1", input$show_me1a_links, "EMTF-1", input$me1a_rl) })
    output$emtf_me1b_n1 <- renderChart({ makeChart("emtf_me1b_n1", input$show_me1b_links, "EMTF-1", input$me1b_rl) })
    output$emtf_me2_n1  <- renderChart({ makeChart("emtf_me2_n1",  input$show_me2_links,  "EMTF-1", input$me2_rl) })
    output$emtf_me3_n1  <- renderChart({ makeChart("emtf_me3_n1",  input$show_me3_links,  "EMTF-1", input$me3_rl) })
    output$emtf_me4_n1  <- renderChart({ makeChart("emtf_me4_n1",  input$show_me4_links,  "EMTF-1", input$me4_rl) })
    output$emtf_men_n1  <- renderChart({ makeChart("emtf_men_n1",  input$show_me4_links,  "EMTF-1", input$men_rl) })
    output$emtf_all_n1  <- renderChart({ makeChart("emtf_all_n1",  input$show_all_links,  "EMTF-1", input$all_rl) })

    output$emtf_me1a_n2 <- renderChart({ makeChart("emtf_me1a_n2", input$show_me1a_links, "EMTF-2", input$me1a_rl) })
    output$emtf_me1b_n2 <- renderChart({ makeChart("emtf_me1b_n2", input$show_me1b_links, "EMTF-2", input$me1b_rl) })
    output$emtf_me2_n2  <- renderChart({ makeChart("emtf_me2_n2",  input$show_me2_links,  "EMTF-2", input$me2_rl) })
    output$emtf_me3_n2  <- renderChart({ makeChart("emtf_me3_n2",  input$show_me3_links,  "EMTF-2", input$me3_rl) })
    output$emtf_me4_n2  <- renderChart({ makeChart("emtf_me4_n2",  input$show_me4_links,  "EMTF-2", input$me4_rl) })
    output$emtf_men_n2  <- renderChart({ makeChart("emtf_men_n2",  input$show_me4_links,  "EMTF-2", input$men_rl) })
    output$emtf_all_n2  <- renderChart({ makeChart("emtf_all_n2",  input$show_all_links,  "EMTF-2", input$all_rl) })

    output$emtf_me1a_n3 <- renderChart({ makeChart("emtf_me1a_n3", input$show_me1a_links, "EMTF-3", input$me1a_rl) })
    output$emtf_me1b_n3 <- renderChart({ makeChart("emtf_me1b_n3", input$show_me1b_links, "EMTF-3", input$me1b_rl) })
    output$emtf_me2_n3  <- renderChart({ makeChart("emtf_me2_n3",  input$show_me2_links,  "EMTF-3", input$me2_rl) })
    output$emtf_me3_n3  <- renderChart({ makeChart("emtf_me3_n3",  input$show_me3_links,  "EMTF-3", input$me3_rl) })
    output$emtf_me4_n3  <- renderChart({ makeChart("emtf_me4_n3",  input$show_me4_links,  "EMTF-3", input$me4_rl) })
    output$emtf_men_n3  <- renderChart({ makeChart("emtf_men_n3",  input$show_me4_links,  "EMTF-3", input$men_rl) })
    output$emtf_all_n3  <- renderChart({ makeChart("emtf_all_n3",  input$show_all_links,  "EMTF-3", input$all_rl) })

    output$emtf_me1a_n4 <- renderChart({ makeChart("emtf_me1a_n4", input$show_me1a_links, "EMTF-4", input$me1a_rl) })
    output$emtf_me1b_n4 <- renderChart({ makeChart("emtf_me1b_n4", input$show_me1b_links, "EMTF-4", input$me1b_rl) })
    output$emtf_me2_n4  <- renderChart({ makeChart("emtf_me2_n4",  input$show_me2_links,  "EMTF-4", input$me2_rl) })
    output$emtf_me3_n4  <- renderChart({ makeChart("emtf_me3_n4",  input$show_me3_links,  "EMTF-4", input$me3_rl) })
    output$emtf_me4_n4  <- renderChart({ makeChart("emtf_me4_n4",  input$show_me4_links,  "EMTF-4", input$me4_rl) })
    output$emtf_men_n4  <- renderChart({ makeChart("emtf_men_n4",  input$show_me4_links,  "EMTF-4", input$men_rl) })
    output$emtf_all_n4  <- renderChart({ makeChart("emtf_all_n4",  input$show_all_links,  "EMTF-4", input$all_rl) })

    output$emtf_me1a_n5 <- renderChart({ makeChart("emtf_me1a_n5", input$show_me1a_links, "EMTF-5", input$me1a_rl) })
    output$emtf_me1b_n5 <- renderChart({ makeChart("emtf_me1b_n5", input$show_me1b_links, "EMTF-5", input$me1b_rl) })
    output$emtf_me2_n5  <- renderChart({ makeChart("emtf_me2_n5",  input$show_me2_links,  "EMTF-5", input$me2_rl) })
    output$emtf_me3_n5  <- renderChart({ makeChart("emtf_me3_n5",  input$show_me3_links,  "EMTF-5", input$me3_rl) })
    output$emtf_me4_n5  <- renderChart({ makeChart("emtf_me4_n5",  input$show_me4_links,  "EMTF-5", input$me4_rl) })
    output$emtf_men_n5  <- renderChart({ makeChart("emtf_men_n5",  input$show_me4_links,  "EMTF-5", input$men_rl) })
    output$emtf_all_n5  <- renderChart({ makeChart("emtf_all_n5",  input$show_all_links,  "EMTF-5", input$all_rl) })

    output$emtf_me1a_n6 <- renderChart({ makeChart("emtf_me1a_n6", input$show_me1a_links, "EMTF-6", input$me1a_rl) })
    output$emtf_me1b_n6 <- renderChart({ makeChart("emtf_me1b_n6", input$show_me1b_links, "EMTF-6", input$me1b_rl) })
    output$emtf_me2_n6  <- renderChart({ makeChart("emtf_me2_n6",  input$show_me2_links,  "EMTF-6", input$me2_rl) })
    output$emtf_me3_n6  <- renderChart({ makeChart("emtf_me3_n6",  input$show_me3_links,  "EMTF-6", input$me3_rl) })
    output$emtf_me4_n6  <- renderChart({ makeChart("emtf_me4_n6",  input$show_me4_links,  "EMTF-6", input$me4_rl) })
    output$emtf_men_n6  <- renderChart({ makeChart("emtf_men_n6",  input$show_me4_links,  "EMTF-6", input$men_rl) })
    output$emtf_all_n6  <- renderChart({ makeChart("emtf_all_n6",  input$show_all_links,  "EMTF-6", input$all_rl) })

    output$emtf_me1a_p1 <- renderChart({ makeChart("emtf_me1a_p1", input$show_me1a_links, "EMTF+1", input$me1a_rl) })
    output$emtf_me1b_p1 <- renderChart({ makeChart("emtf_me1b_p1", input$show_me1b_links, "EMTF+1", input$me1b_rl) })
    output$emtf_me2_p1  <- renderChart({ makeChart("emtf_me2_p1",  input$show_me2_links,  "EMTF+1", input$me2_rl) })
    output$emtf_me3_p1  <- renderChart({ makeChart("emtf_me3_p1",  input$show_me3_links,  "EMTF+1", input$me3_rl) })
    output$emtf_me4_p1  <- renderChart({ makeChart("emtf_me4_p1",  input$show_me4_links,  "EMTF+1", input$me4_rl) })
    output$emtf_men_p1  <- renderChart({ makeChart("emtf_men_p1",  input$show_me4_links,  "EMTF+1", input$men_rl) })
    output$emtf_all_p1  <- renderChart({ makeChart("emtf_all_p1",  input$show_all_links,  "EMTF+1", input$all_rl) })

    output$emtf_me1a_p2 <- renderChart({ makeChart("emtf_me1a_p2", input$show_me1a_links, "EMTF+2", input$me1a_rl) })
    output$emtf_me1b_p2 <- renderChart({ makeChart("emtf_me1b_p2", input$show_me1b_links, "EMTF+2", input$me1b_rl) })
    output$emtf_me2_p2  <- renderChart({ makeChart("emtf_me2_p2",  input$show_me2_links,  "EMTF+2", input$me2_rl) })
    output$emtf_me3_p2  <- renderChart({ makeChart("emtf_me3_p2",  input$show_me3_links,  "EMTF+2", input$me3_rl) })
    output$emtf_me4_p2  <- renderChart({ makeChart("emtf_me4_p2",  input$show_me4_links,  "EMTF+2", input$me4_rl) })
    output$emtf_men_p2  <- renderChart({ makeChart("emtf_men_p2",  input$show_me4_links,  "EMTF+2", input$men_rl) })
    output$emtf_all_p2  <- renderChart({ makeChart("emtf_all_p2",  input$show_all_links,  "EMTF+2", input$all_rl) })

    output$emtf_me1a_p3 <- renderChart({ makeChart("emtf_me1a_p3", input$show_me1a_links, "EMTF+3", input$me1a_rl) })
    output$emtf_me1b_p3 <- renderChart({ makeChart("emtf_me1b_p3", input$show_me1b_links, "EMTF+3", input$me1b_rl) })
    output$emtf_me2_p3  <- renderChart({ makeChart("emtf_me2_p3",  input$show_me2_links,  "EMTF+3", input$me2_rl) })
    output$emtf_me3_p3  <- renderChart({ makeChart("emtf_me3_p3",  input$show_me3_links,  "EMTF+3", input$me3_rl) })
    output$emtf_me4_p3  <- renderChart({ makeChart("emtf_me4_p3",  input$show_me4_links,  "EMTF+3", input$me4_rl) })
    output$emtf_men_p3  <- renderChart({ makeChart("emtf_men_p3",  input$show_me4_links,  "EMTF+3", input$men_rl) })
    output$emtf_all_p3  <- renderChart({ makeChart("emtf_all_p3",  input$show_all_links,  "EMTF+3", input$all_rl) })

    output$emtf_me1a_p4 <- renderChart({ makeChart("emtf_me1a_p4", input$show_me1a_links, "EMTF+4", input$me1a_rl) })
    output$emtf_me1b_p4 <- renderChart({ makeChart("emtf_me1b_p4", input$show_me1b_links, "EMTF+4", input$me1b_rl) })
    output$emtf_me2_p4  <- renderChart({ makeChart("emtf_me2_p4",  input$show_me2_links,  "EMTF+4", input$me2_rl) })
    output$emtf_me3_p4  <- renderChart({ makeChart("emtf_me3_p4",  input$show_me3_links,  "EMTF+4", input$me3_rl) })
    output$emtf_me4_p4  <- renderChart({ makeChart("emtf_me4_p4",  input$show_me4_links,  "EMTF+4", input$me4_rl) })
    output$emtf_men_p4  <- renderChart({ makeChart("emtf_men_p4",  input$show_me4_links,  "EMTF+4", input$men_rl) })
    output$emtf_all_p4  <- renderChart({ makeChart("emtf_all_p4",  input$show_all_links,  "EMTF+4", input$all_rl) })

    output$emtf_me1a_p5 <- renderChart({ makeChart("emtf_me1a_p5", input$show_me1a_links, "EMTF+5", input$me1a_rl) })
    output$emtf_me1b_p5 <- renderChart({ makeChart("emtf_me1b_p5", input$show_me1b_links, "EMTF+5", input$me1b_rl) })
    output$emtf_me2_p5  <- renderChart({ makeChart("emtf_me2_p5",  input$show_me2_links,  "EMTF+5", input$me2_rl) })
    output$emtf_me3_p5  <- renderChart({ makeChart("emtf_me3_p5",  input$show_me3_links,  "EMTF+5", input$me3_rl) })
    output$emtf_me4_p5  <- renderChart({ makeChart("emtf_me4_p5",  input$show_me4_links,  "EMTF+5", input$me4_rl) })
    output$emtf_men_p5  <- renderChart({ makeChart("emtf_men_p5",  input$show_me4_links,  "EMTF+5", input$men_rl) })
    output$emtf_all_p5  <- renderChart({ makeChart("emtf_all_p5",  input$show_all_links,  "EMTF+5", input$all_rl) })

    output$emtf_me1a_p6 <- renderChart({ makeChart("emtf_me1a_p6", input$show_me1a_links, "EMTF+6", input$me1a_rl) })
    output$emtf_me1b_p6 <- renderChart({ makeChart("emtf_me1b_p6", input$show_me1b_links, "EMTF+6", input$me1b_rl) })
    output$emtf_me2_p6  <- renderChart({ makeChart("emtf_me2_p6",  input$show_me2_links,  "EMTF+6", input$me2_rl) })
    output$emtf_me3_p6  <- renderChart({ makeChart("emtf_me3_p6",  input$show_me3_links,  "EMTF+6", input$me3_rl) })
    output$emtf_me4_p6  <- renderChart({ makeChart("emtf_me4_p6",  input$show_me4_links,  "EMTF+6", input$me4_rl) })
    output$emtf_men_p6  <- renderChart({ makeChart("emtf_men_p6",  input$show_me4_links,  "EMTF+6", input$men_rl) })
    output$emtf_all_p6  <- renderChart({ makeChart("emtf_all_p6",  input$show_all_links,  "EMTF+6", input$all_rl) })

  }
)
