---
title       : "L1T O2O status"
subtitle    : 
author      : Khristian Kotov
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
github:
  user: kkotov 
  repo: talks
url:
  lib:    ../../../../monohiggs/plots/libraries
  assets: ../../../../monohiggs/plots/assets
widgets     : [mathjax]     # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
--- &twocol

## Recap of L1T O2O in 2016

L1 trigger upgrade of 2015 rendered obsolete all of the system-specific O2O code

New code was gradually put in place through summer while running in the development mode
(the run-critical uGT/L1Menu was prepared already in 2015 and always ran in production)

In the end of 2016 all (but CaloParams) payloads/tags were moved from Dev DB to Prod DB:

*** =left

System     |   Payload[Tag]
-----------|-----------------
uGT        | <span style="font-weight:bold;font-size:smaller;color:green">L1TUtmTriggerMenu[_Stage2v0_hlt]</span>
uGT RS     | <span style="font-weight:bold;font-size:smaller;color:green">L1TGlobalPrescalesVetos[_Stage2v0_hlt]</span>
CALOL{1,2} | <span style="font-weight:bold;font-size:smaller;color:red">L1TCaloParams[_Stage2v0_hlt]</span>
uGMT       | <span style="font-weight:bold;font-size:smaller;color:green">L1TMuonGlobalParams[_Stage2v0_hlt]</span>

*** =right

System     |   Payload[Tag]
-----------|-----------------
BMTF       | <span style="font-weight:bold;font-size:smaller;color:green">L1TMuonBarrelParams[_Stage2v0_hlt]</span>
OMTF       | <span style="font-weight:bold;font-size:smaller;color:green">L1TMuonOverlapParams[_Stage2v0_hlt]</span>
EMTF       | <span style="font-weight:bold;font-size:smaller;color:green">L1TMuonEndCapParams[_Stage2v0_hlt]</span>
O2O        | <span style="font-weight:bold;font-size:smaller;color:blue">L1TriggerKey(List)[_Stage2v0_hlt]</span>

*** =fullwidth
<br>

Additional <span style="font-weight:bold;font-size:smaller;color:green">L1TMuonEndCapForests[_Stage2v0_hlt]</span>
payload was prepared for EMTF but never used as the pT LUT never changed in 2016 (expected to change in 2017)

--- .class #id

## L1T O2O infrastructure 

Job is invoked by SWATCH central cell in the end of configuration cycle and does the following:
* with the given TSC key it navigates through subsystem tables and fetches the XMLs
  (online DB offers 3 tables per subsystem as explained in [slide 5](https://indico.cern.ch/event/591003/contributions/2384788/attachments/1378957/2095301/L1TriggerDatabase_v2.pdf))
* it parses the XMLs and packs offline-relevant parameters in payloads
* it pushes the payloads to offline DB and stamps them with run-based IOV ([slide 4](http://kkotov.github.io/l1o2o/talks/2016.04.19/#4))

One of the requirement is to start with pre-initialized payloads (CMSSW static configs or prototype payloads)
and override a subset of parameters with values extracted from online DB 

In a nutshell the L1T O2O is a CMSSW job wrapped in series of scripts ([slide 5](http://kkotov.github.io/l1o2o/talks/2015.04.20/#5))

--- .class #id

## New L1T O2O features

O2O can be ran on lxplus provided you have the DB access token (great for testing!):
* <span style="font-family:monospace">./runL1-O2O-iov.sh 285832 collisions2016_TSC/v206 collisions2016_RS/v291</span>

Splitting a monolithic job in a [sequence per-payload jobs](https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/L1TriggerConfig/Utilities/test/runOneByOne.sh) doubles running time (13s $\rightarrow$ 25s)
* for per-payload monitoring I'd prefer mimicking multiple jobs by splitting logs of one job

Tag name for any payloads can be changed with an argument (PR #[17641](https://github.com/cms-sw/cmssw/pull/17641) to be merged)
* example: <span style="font-family:monospace;font-size:smaller;color:green">-t L1TCaloParams:Stage2v1_hlt,L1TMuonEndCap:TestTag</span> instructs O2O to
override the [standard suffixes](https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/CondTools/L1TriggerExt/python/L1O2OTagsExt_cfi.py)
and produce <span style="font-family:monospace;font-size:smaller;color:green">L1TCaloParams_Stage2v1_hlt</span>
and <span style="font-family:monospace;font-size:smaller;color:green">L1TMuonEndCap_TestTag</span> tags

--- .class #id

## Subsystem-specific workflows and comments

<span style="font-weight:bold;color:brown">uGT:</span>
[UTM XML-parsing library](https://gitlab.cern.ch/cms-l1t-utm/utm) changes when new triggers are introduced in L1Menu
* as agreed with AlCa, the library update comes only with a new central CMSSW installation

<span style="font-weight:bold;color:brown">uGTrs:</span>
manually composed XML with errors crashed L1T O2O few times before
* with the new L1CE service and new FM policy this problem is not expected to reoccur

<span style="font-weight:bold;color:brown">CALO:</span>
eta-compress LUT not in online DB (updated once) $\rightarrow$ experts 
[keep-in-synch](https://github.com/cms-sw/cmssw/blob/CMSSW_9_0_X/L1TriggerConfig/Utilities/test/uploadCaloParams.py) prototype 

<span style="font-weight:bold;color:brown">OMTF:</span> no online configuration, new firmware on any change needed, but no changes in 2016
* OMTF online software doesn't check FW version wrt. online DB $\rightarrow$ O2O does nothing

<span style="font-weight:bold;color:brown">EMTF:</span> as in OMTF, firmware changes as opposed to online configs, except for 2GB pT LUT
* online software checks LUT version wrt. online DB $\rightarrow$ meta-LUTs (Forests) to be added ...
 
<span style="font-weight:bold;color:brown">uGMT</span> and <span style="font-weight:bold;color:brown">BMTF</span> are the most streamlined O2O components without special requirements

--- .class #id


## To do list

<span style="font-weight:bold;color:brown">uGT:</span> track down and fix
<span style="font-weight:bold;font-size:smaller;color:green">LL1TUtmTriggerMenu</span> hash sum instability reappearing in 90X
* in 80X all uninitialized fields were identified and initialized
* in 90X I saw once again that launching same O2O job may give different hash sums

<span style="font-weight:bold;color:brown">CALO:</span> scrutinize O2O code for parameters that are not yet translated to the payload
* looks like we don't have some parameters introduced in late 2016 (e.g. egHOverEcut*)

<span style="font-weight:bold;color:brown">EMTF:</span> add pT LUT EventSetup configurability to the new emulator (as opposed to release XMLs)
* new FW version at p5, although O2Oed, is not very useful if unknown to the emulator
* contrary, pT LUT "Forests" result from an offline study and need to be pushed in CondDB
* an old PR #[426](https://github.com/cms-l1t-offline/cmssw/pull/426) needs to be "married" with the new emulator's code

--- .class #id


## L1T tags for data GTs (online's history of 2016)

Performance plots for [muons](https://its.cern.ch/jira/browse/CMSLITDPG-3) and [calo](https://its.cern.ch/jira/browse/CMSLITDPG-4)
show data/emulator agreement for Heavy Ion runs

Besides L1TMenu and prescales/vetos following tags need to be aggregated by Global Tags:

<span style="font-weight:bold;color:brown">uGMT:</span>
[L1TMuonGlobalParams_Stage2v0_hlt](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonGlobalParams_Stage2v0_hlt)

<span style="font-weight:bold;color:brown">BMTF:</span>
[L1TMuonBarrelParams_Stage2v0_hlt](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonBarrelParams_Stage2v0_hlt)

<span style="font-weight:bold;color:brown">OMTF:</span>
[L1TMuonOverlapParams_Stage2v0_hlt](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonOverlapParams_Stage2v0_hlt)

A special case:

<span style="font-weight:bold;color:brown">CALO:</span>
[L1TCaloParams_Stage2v0_hlt_HI2016](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TCaloParams_Stage2v0_hlt_HI2016) - fully validated tag for Heavy Ions 
and end-of-2016 $pp$ runs, e.g.:

[e/gamma ET](EgEt.pdf)
[e/gamma eta](EgEta.pdf)
[e/gamma phi](EgPhi.pdf)

(sorry for the pdf format)

--- .class #id


## Clibration constants

https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TStage2Instructions#L1REPACK_step_with_cmsDriver_com

--- .class #id

## Moving from static pythons to CondDB configs

<br>
L1T emulators always ran with static pythons

Before we choose CondDB configuration as our default, we've made a closure test

The emulators were tested with payloads generated from static pythons

--- .class #id


## A snapshot of static config pushed to CondDB

As a first step towards configuring L1T emulators from CondDB I've produced
the following tags from fake producer and static files in v91.12:

<span style="font-weight:bold;color:brown">uGTrs:</span>
[L1TGlobalPrescalesVetos_passThrough](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TGlobalPrescalesVetos_passThrough)
* a single prescale set with all prescales = 1 and disabled masks/vetos 

<span style="font-weight:bold;color:brown">CALO:</span>
[L1TCaloStage2Params_static_v91.12_v3_3_1](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TCaloStage2Params_static_v91.12_v3_3_1)

<span style="font-weight:bold;color:brown">uGMT:</span>
[L1TMuonGlobalParams_static_v91.12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonGlobalParams_static_v91.12)

<span style="font-weight:bold;color:brown">BMTF:</span>
[L1TMuonBarrelParams_static_v91.12](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonBarrelParams_static_v91.12)

<span style="font-weight:bold;color:brown">OMTF:</span>
[L1TMuonOverlapParams_Stage2v0_hlt](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonOverlapParams_Stage2v0_hlt)

Additionally, HI payload for <span style="font-weight:bold;color:brown">CALO</span>:
[L1TCaloStage2Params_static_v91.12_v3_3_1_HI](https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TCaloStage2Params_static_v91.12_v3_3_1_HI)

The closure test shows 100% agreement with statics (as expected)
